version = 0.1

[default.deploy.parameters]
stack_name = "task-manger-with-bot"
resolve_s3 = true
s3_prefix = "task-manger-with-bot"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
