AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Task manager with health + tasks CRUD

Globals:
  Function:
    Runtime: nodejs20.x
    Timeout: 30
    MemorySize: 512
    Tracing: Active
    Environment:
      Variables:
        TASKS_TABLE: !Ref TasksTable
        AWS_NODEJS_CONNECTION_REUSE_ENABLED: '1'
  Api:
    Cors:
      AllowMethods: "'GET,POST,PUT,DELETE,OPTIONS'"
      AllowHeaders: "'Content-Type,Authorization'"
      AllowOrigin: "'*'"

Resources:
  # ---- DynamoDB table for tasks ----
  TasksTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST         # on-demand
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      TableClass: STANDARD

  # ---- Health function (from Step 1) ----
  HealthFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: health/
      Handler: index.handler
      Events:
        HealthGet:
          Type: Api
          Properties:
            Path: /health
            Method: GET

  # ---- Tasks function: CRUD ----
  TasksFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: tasks/
      Handler: index.handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref TasksTable
      Events:
        ListTasks:
          Type: Api
          Properties: 
            Path: /tasks
            Method: GET 
        CreateTask:
          Type: Api
          Properties: 
            Path: /tasks
            Method: POST 
        UpdateTask:
          Type: Api
          Properties: 
            Path: /tasks/{id} 
            Method: PUT 
        DeleteTask:
          Type: Api
          Properties:
            Path: /tasks/{id}
            Method: DELETE 
  
  ChatFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: chat/
      Handler: index.handler
      Environment:
        Variables:
          BEDROCK_REGION: us-east-1
          BEDROCK_MODEL_ID: anthropic.claude-3-haiku-20240307-v1:0
      Policies:
        # Allow invoking Bedrock models
        - Statement:
            - Effect: Allow
              Action:
                - bedrock:InvokeModel
              Resource: "*"
      Events:
        ChatPost:
          Type: Api
          Properties:
            Path: /chat
            Method: POST

Outputs:
  ApiUrl:
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod"
    Description: Invoke URL for API Gateway
  TasksTableName:
    Value: !Ref TasksTable
